import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: Readonly<React.ReactNode>;
};

export default async function RootLayout({ children }: Props) {
  return (
    <html lang="bg">
      <body>
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
